teams:
  cli-experimental-admins:
    description: admin access to cli-experimental
    members:
    - KnVerey
    - pwittrock
    - seans3
    - soltysh
    privacy: closed
    repos:
      cli-experimental: admin
  cli-experimental-maintainers:
    description: write access to cli-experimental
    members:
    - liggitt
    privacy: closed
    repos:
      cli-experimental: write
  cli-utils-admins:
    description: admin access to cli-utils
    members:
    - eddiezane
    - knverey
    - seans3
    - soltysh
    privacy: closed
    repos:
      cli-utils: admin
  cli-utils-maintainers:
    description: write access to cli-utils
    members:
    - karlkfi
    - liggitt
    - mortent
    privacy: closed
    repos:
      cli-utils: write
  krew-admins:
    description: admin access to krew
    members:
    - ahmetb
    - chriskim06
    - pwittrock
    - seans3
    - soltysh
    privacy: closed
    repos:
      krew: admin
  krew-maintainers:
    description: write access to krew
    members:
    - ahmetb
    - chriskim06
    - pwittrock
    - seans3
    - soltysh
    privacy: closed
    repos:
      krew: write
  krew-index-admins:
    description: admin access to krew-index
    members:
    - ahmetb
    - chriskim06
    - pwittrock
    - seans3
    - soltysh
    privacy: closed
    repos:
      krew-index: admin
  krew-index-maintainers:
    description: write access to krew-index
    members:
    - ahmetb
    - chriskim06
    - pwittrock
    - seans3
    - soltysh
    privacy: closed
    repos:
      krew-index: write
  krm-functions-registry-admins:
    description: admin access to krm-functions-registry
    members:
    - jeremyrickard
    - KnVerey
    - mengqiy
    privacy: closed
    repos:
      krm-functions-registry: admin
  krm-functions-registry-maintainers:
    description: write access to krm-functions-registry
    members:
    - jeremyrickard
    - KnVerey
    - mengqiy
    - natasha41575
    privacy: closed
    repos:
      krm-functions-registry: write
  kubectl-validate-admins:
    description: admin access to kubectl-validate
    members:
    - alexzielenski
    - apelisse
    privacy: closed
    repos:
      kubectl-validate: admin
  kubectl-validate-maintainers:
    description: write access to kubectl-validate
    members:
    - alexzielenski
    - apelisse
    privacy: closed
    repos:
      kubectl-validate: write
  kui-admins:
    description: admin access to kui
    members:
    - myan9
    - starpit
    privacy: closed
    repos:
      kui: admin
  kui-maintainers:
    description: write access to kui
    members:
    - eddiezane
    - myan9
    - pwittrock
    - seans3
    - soltysh
    - starpit
    privacy: closed
    repos:
      kui: write
  kustomize-admins:
    description: ""
    members:
    - knverey
    - koba1t
    privacy: closed
    repos:
      kustomize: admin
  kustomize-maintainers:
    description: ""
    members:
      - varshaprasad96
    privacy: closed
    repos:
      kustomize: maintain
