teams:
  sig-cli-leads:
    description: ""
    members:
    - ardaguclu
    - eddiezane
    - mpuckett159
    - soltysh
    privacy: closed
  sig-cli-kubectl-maintainers:
    description: ""
    members:
    - ardaguclu
    - brianpursley
    - eddiezane
    - mpuckett159
    - soltysh
    privacy: closed
    repos:
      kubectl: write
