teams:
  custom-metrics-apiserver-admins:
    description: Admin access to the custom-metrics-apiserver repo
    members:
    - dgrisonnet
    privacy: closed
  custom-metrics-apiserver-maintainers:
    description: Write access to the custom-metrics-apiserver repo
    members:
    - dgrisonnet
    privacy: closed
  instrumentation-admins:
    description: Admin access to the instrumentation repo
    members:
    - dashpole
    - dgrisonnet
    - ehashman
    - logicalhan
    privacy: closed
  instrumentation-tools-admins:
    description: Admin access to the instrumentation-tools repo
    members:
    - dashpole
    - dgrisonnet
    - ehashman
    - logicalhan
    privacy: closed
  instrumentation-tools-maintainers:
    description: Write access to the instrumentation-tools repo
    members:
    - dashpole
    - dgrisonnet
    - ehashman
    - logicalhan
    privacy: closed
  logtools-admins:
    description: Admin access to the logtools repo
    members:
      - ehashman
      - logicalhan
      - pohly
      - serathius
    privacy: closed
  logtools-maintainers:
    description: Write access to the logtools repo
    members:
      - ehashman
      - logicalhan
      - pohly
      - serathius
    privacy: closed
  metrics-server-admins:
    description: Admin access to the metrics-server repo
    members:
    - dgrisonnet
    - serathius
    privacy: closed
  metrics-server-maintainers:
    description: Write access to the metrics-server repo
    members:
    - dgrisonnet
    - serathius
    privacy: closed
  prometheus-adapter-admins:
    description: Admin access to the prometheus-adapter repo
    members:
    - dgrisonnet
    privacy: closed
  prometheus-adapter-maintainers:
    description: Write access to the prometheus-adapter repo
    members:
    - dgrisonnet
    privacy: closed
  usage-metrics-collector-admins:
    description: Admin access to the usage-metrics-collector repo
    members:
    - campoy
    - ehashman
    - KnVerey
    - ndipebot
    - pmorie
    - pwittrock
    privacy: closed
  usage-metrics-collector-maintainers:
    description: Write access to the usage-metrics-collector repo
    members:
    - campoy
    - ehashman
    - KnVerey
    - ndipebot
    - pmorie
    - pwittrock
    privacy: closed
