teams:
  execution-hook-admins:
    description: Admin access to execution-hook repo
    members:
    - kow3ns
    - liyinan926
    privacy: closed
  execution-hook-maintainers:
    description: Write access to execution-hook repo
    members:
    - jingxu97
    - kow3ns
    - liyinan926
    - xing-yang
    privacy: closed
  jobset-admins:
    description: Admin access to jobset repo
    members:
    - ahg-g
    - danielvegamyhre
    privacy: closed
  jobset-maintainers:
    description: Write access to jobset repo
    members:
    - ahg-g
    privacy: closed
