teams:
  aws-ebs-csi-driver-admins:
    description: ""
    members:
    - ConnorJC3
    - gtxu
    - hanyuel
    - leakingtapan
    - rdpsin
    - torredil
    - wongma7
    privacy: closed
  aws-ebs-csi-driver-maintainers:
    description: ""
    members:
    - AndyXiangLi
    - bertinatto
    - ConnorJC3
    - gnufied
    - gtxu
    - hanyuel
    - jsafrane
    - leakingtapan
    - nirmalaagash
    - rdpsin
    - torredil
    - wongma7
    privacy: closed
  aws-encryption-provider-admins:
    description: admin access to aws_encryption-provider repo
    members:
    - justinsb
    - micahhausler
    - nckturner
    - wongma7
    privacy: closed
  aws-encryption-provider-maintainers:
    description: write access to aws_encryption-provider
    members:
    - justinsb
    - micahhausler
    - nckturner
    - wongma7
    privacy: closed
  aws-fsx-csi-driver-admins:
    description: admin access to aws-fsx-csi-driver
    members:
    - justinsb
    - khoang98
    - leakingtapan
    - wongma7
    privacy: closed
  aws-fsx-csi-driver-maintainers:
    description: write access to aws-fsx-csi-driver
    members:
    - d-nishi
    - jsafrane
    - justinsb
    - khoang98
    - leakingtapan
    - wongma7
    privacy: closed
  aws-efs-csi-driver-admins:
    description: admin access to aws-efs-csi-driver
    members:
    - Ashley-wenyizha
    - justinsb
    - leakingtapan
    - wongma7
    privacy: closed
  aws-efs-csi-driver-maintainers:
    description: write access to aws-efs-csi-driver
    members:
    - Ashley-wenyizha
    - d-nishi
    - jsafrane
    - justinsb
    - leakingtapan
    - wongma7
    privacy: closed
