teams:
  cluster-proportional-autoscaler-admins:
    description: Admin access to the cluster-proportional-autoscaler repo
    members:
    - bowei
    - MrHohn
    - thockin
    privacy: closed
  cluster-proportional-autoscaler-maintainers:
    description: Write access to the cluster-proportional-autoscaler repo
    members:
    - bowei
    - MrHohn
    - thockin
    privacy: closed
  cluster-proportional-vertical-autoscaler-admins:
    description: Admin access to the cluster-proportional-autoscaler repo
    members:
    - bowei
    - MrHohn
    - thockin
    privacy: closed
  cluster-proportional-vertical-autoscaler-maintainers:
    description: Admin access to the cluster-proportional-autoscaler repo
    members:
    - bowei
    - MrHohn
    - thockin
    privacy: closed
  ip-masq-agent-admins:
    description: Admin access to the ip-masq-agent repo
    members:
    - bowei
    - MrHohn
    privacy: closed
    previously:
    - admins-ip-masq-agent
  ip-masq-agent-maintainers:
    description: Write access to the ip-masq-agent repo
    members:
    - bowei
    - MrHohn
    privacy: closed
    previously:
    - maintainers-ip-masq-agent
  external-dns-admins:
    description: Admin access to the external-dns repo
    members:
    - linki
    - njuettner
    - Raffo
    - szuecs
    privacy: closed
    previously:
    - admins-external-dns
  external-dns-maintainers:
    description: Write access to the external-dns repo
    members:
    - linki
    - njuettner
    - Raffo
    - seanmalloy
    - szuecs
    privacy: closed
    previously:
    - maintainers-external-dns
  ingress2gateway-admins:
    description: Admin access to the ingress2gateway repo
    members:
    - bowei
    - robscott
    - shaneutt
    - youngnick
    privacy: closed
  ingress2gateway-maintainers:
    description: Write access to the ingress2gateway repo
    members:
    - bowei
    - robscott
    - shaneutt
    - youngnick
    privacy: closed
  ingress-controller-conformance-admins:
    description: Admin access to the ingress-controller-conformance repo
    members:
    - alexgervais
    - bowei
    - thockin
    privacy: closed
    previously:
    - admins-ingress-controller-conformance
  ingress-controller-conformance-maintainers:
    description: Write access to the ingress-controller-conformance repo
    members:
    - alexgervais
    - bowei
    - thockin
    privacy: closed
    previously:
    - maintainers-ingress-controller-conformance
  iptables-wrappers-admins:
    description: Admin access to the iptables-wrappers repo
    members:
    - caseydavenport
    - danwinship
    - dcbw
    - thockin
    privacy: closed
  iptables-wrappers-maintainers:
    description: Write access to the iptables-wrappers repo
    members:
    - caseydavenport
    - danwinship
    - dcbw
    - thockin
    privacy: closed
  gateway-api-admins:
    description: Admin access to the gateway-api repo
    members:
    - bowei
    - robscott
    - shaneutt
    - youngnick
    privacy: closed
    previously:
    - service-apis-admins
  gateway-api-maintainers:
    description: Write access to the gateway-api repo
    members:
    - bowei
    - robscott
    - shaneutt
    - youngnick
    privacy: closed
    previously:
    - service-apis-maintainers
    - service-apis-amintainers
  gateway-api-mesh-leads:
    description: Write access to the gateway-api repo
    members:
    - howardjohn
    - keithmattix
    - mikemorris
    privacy: closed
  kpng-admins:
    description: Admin access to the kpng repo
    members:
    - mcluseau
    - thockin
    privacy: closed
  network-policy-api-admins:
    description: Admin access to the network-policy-api repo
    members:
    - astoycos
    - danwinship
    - Dyanngg
    privacy: closed
