teams:
  dra-example-driver-admins:
    description: Admin access to dra-example-driver repo
    members:
    - klueska
    - pohly
    privacy: closed
  dra-example-driver-maintainers:
    description: Write access to dra-example-driver repo
    members:
    - bart0sh
    privacy: closed
  node-feature-discovery-operator-admins:
    description: Admin access to node-feature-discovery-operator repo
    members:
    - ArangoGutierrez
    - marquiz
    - zvonkok
    privacy: closed
  node-feature-discovery-operator-maintainers:
    description: Write access to node-feature-discovery-operator repo
    members:
    - ArangoGutierrez
    - marquiz
    - zvonkok
    privacy: closed
  noderesourcetopology-api-admins:
    description: Admin access to noderesourcetopology-api repo
    members:
    - ffromani
    - swatisehgal
    privacy: closed
  noderesourcetopology-api-maintainers:
    description: Write access to noderesourcetopology-api repo
    members:
    - marquiz
    privacy: closed
  security-profiles-operator-admins:
    description: Admin access to security-profiles-operator repo
    members:
    - ccojocar
    - JAORMX
    - jhrozek
    - pjbgf
    - saschagrunert
    privacy: closed
    previously:
    - seccomp-operator-admins
  security-profiles-operator-maintainers:
    description: Write access to security-profiles-operator repo
    members:
    - ccojocar
    - JAORMX
    - jhrozek
    - pjbgf
    - saschagrunert
    privacy: closed
    previously:
    - seccomp-operator-maintainers
  kernel-module-management-admins:
    description: Admin access to kernel-module-management repo
    members:
    - qbarrand
    - yevgeny-shnaidman
    privacy: closed
    previously:
    - special-resource-operator-admins
  kernel-module-management-maintainers:
    description: Write access to kernel-module-management repo
    members:
    - qbarrand
    - yevgeny-shnaidman
    privacy: closed
    previously:
    - special-resource-operator-maintainers
