teams:
  sig-autoscaling-api-reviews:
    description: ""
    members:
    - MaciekPytel
    - mwielgus
    privacy: closed
  sig-autoscaling-bugs:
    description: ""
    members:
    - MaciekPytel
    - mwielgus
    privacy: closed
  sig-autoscaling-feature-requests:
    description: ""
    members:
    - MaciekPytel
    - mwielgus
    privacy: closed
  sig-autoscaling-misc:
    description: ""
    members:
    - MaciekPytel
    - mwielgus
    privacy: closed
  sig-autoscaling-pr-reviews:
    description: ""
    members:
    - MaciekPytel
    - mwielgus
    privacy: closed
  sig-autoscaling-proposals:
    description: ""
    members:
    - MaciekPytel
    - mwielgus
    privacy: closed
  sig-autoscaling-test-failures:
    description: ""
    members:
    - MaciekPytel
    - mwielgus
    privacy: closed
  sig-autoscaling-leads:
    description: ""
    members:
    - gjtempleton
    - mwielgus
    privacy: closed
