teams:
  community-images-admins:
    description: admins access to community-images
    members:
    - ameukam
    - dims
    - spiffxp
    - thockin
    privacy: closed
  community-images-writers:
    description: write access to community-images
    members:
      - ameukam
      - dims
      - spiffxp
      - thockin
    privacy: closed
  community-images-maintainers:
    description: write access to community-images
    members:
    - ameukam
    - dims
    - spiffxp
    - thockin
    privacy: closed
  porche-admins:
    description: admins access to porche
    members:
    - ameukam
    - bentheelder
    - dims
    - justinsb
    - spiffxp
    - thockin
    privacy: closed
  porche-writers:
    description: write access to porche
    members:
      - ameukam
      - bentheelder
      - dims
      - justinsb
      - spiffxp
      - thockin
    privacy: closed
  porche-maintainers:
    description: write access to porche
    members:
    - ameukam
    - bentheelder
    - dims
    - justinsb
    - spiffxp
    - thockin
    privacy: closed
