teams:
  depstat-admins:
    description: Admin access to depstat repo
    maintainers:
    - nikhita
    members:
    - dims
    - navidshaikh
    - RinkiyaKeDad
    privacy: closed
    repos:
      depstat: admin
  apisnoop-admins:
    description: Admin access to apisnoop repo
    members:
    - BobyMCbobs
    - cooldracula
    - heyste
    - hh
    privacy: closed
    repos:
      apisnoop: admin
  apisnoop-maintainers:
    description: Write access to apisnoop repo
    members:
    - BobyMCbobs
    - cooldracula
    - heyste
    - hh
    privacy: closed
    repos:
      apisnoop: write
