teams:
  contributor-tweets-admins:
    description: admin access to contributor-tweets
    maintainers:
    - cblecker
    - mrbobbytables
    - nikhita
    members:
    - chris-short
    - kaslin
    privacy: closed
  contributor-tweets-maintainers:
    description: write access to contributor-tweets
    maintainers:
    - cblecker
    - mrbobbytables
    - nikhita
    members:
    - castrojo
    privacy: closed
  discuss-theme-admins:
    description: admin access to the discuss-theme repo
    maintainers:
    - mrbobbytables
    members:
    - castrojo
    privacy: closed
  discuss-theme-maintainers:
    description: write access to the discuss-theme repo
    maintainers:
    - mrbobbytables
    members:
    - castrojo
    privacy: closed
  lwkd-admins:
    description: admin access to the lwkd repo
    members:
    - coderanger
    - jberkus
    privacy: closed
  lwkd-maintainers:
    description: write access to the lwkd repo
    members:
    - coderanger
    - jberkus
    privacy: closed
  maintainers-admins:
    description: admin access to the maintainers repo
    maintainers:
    - nikhita
    members:
    - dims
    privacy: closed
  maintainers-maintainers:
    description: write access to the maintainers repo
    maintainers:
    - MadhavJivrajani
    - mrbobbytables
    - nikhita
    - palnabarun
    members:
    - dims
    privacy: closed
  slack-infra-admins:
    description: admin access to slack-infra
    members:
    - jeefy
    - Katharine
    privacy: closed
