teams:
  cluster-addons-admins:
    description: admin access to cluster-addons
    members:
    - justinsb
    - luxas
    - roberthbailey
    - timothysc
    privacy: closed
    previously:
    - addon-operators-admins
  cluster-addons-maintainers:
    description: write access to cluster-addons
    members:
    - justinsb
    - stealthybox
    privacy: closed
    previously:
    - addon-operators-maintainers
  cluster-api-addon-provider-helm-admins:
    description:  Admin access to cluster-api-addon-provider-helm repo
    members:
    - CecileRobertMichon
    - fabriziopandini
    - jackfrancis
    - Jont828
    privacy: closed
  cluster-api-addon-provider-helm-maintainers:
    description: Write access to cluster-api-addon-provider-helm repo
    members:
    - CecileRobertMichon
    - fabriziopandini
    - jackfrancis
    - Jont828
    privacy: closed
  cluster-api-admins:
    description: ""
    members:
    - CecileRobertMichon
    - fabriziopandini
    - sbueringer
    - vincepri
    privacy: closed
  cluster-api-maintainers:
    description: ""
    members:
    - CecileRobertMichon
    - enxebre
    - fabriziopandini
    - killianmuldoon
    - sbueringer
    - vincepri
    privacy: closed
  cluster-api-ipam-provider-in-cluster-admins:
    description: "admin access to cluster-api-ipam-provider-in-cluster"
    members:
    - CecileRobertMichon
    - fabriziopandini
    - schrej
    privacy: closed
  cluster-api-operator-admins:
    description: "admin access to cluster-api-operator"
    members:
    - alexander-demicev
    - damdo
    - Fedosin
    - JoelSpeed
    privacy: closed
  cluster-api-provider-aws-admins:
    description: admin access to cluster-api-provider-aws
    members:
    - richardcase
    - sedefsavas
    privacy: closed
  cluster-api-provider-aws-maintainers:
    description: write access to cluster-api-provider-aws
    members:
    - Ankitasw
    - dlipovetsky
    - richardcase
    - sedefsavas
    - Skarlso
    privacy: closed
  cluster-api-provider-azure-admins:
    description: ""
    members:
    - alexeldeib
    - CecileRobertMichon
    - devigned
    - jackfrancis
    - mboersma
    - shysank
    privacy: closed
  cluster-api-provider-azure-maintainers:
    description: ""
    members:
    - alexeldeib
    - CecileRobertMichon
    - devigned
    - jackfrancis
    - mboersma
    - shysank
    privacy: closed
  cluster-api-provider-azure-pms:
    description: ""
    members:
    - CecileRobertMichon
    - devigned
    - dtzar
    - jackfrancis
    - Jont828
    - jsturtevant
    - marosset
    - mboersma
    - nawazkh
    - nojnhuh
    - sonasingh46
    - willie-yao
    privacy: closed
  cluster-api-provider-cloudstack-admins:
    description: ""
    members:
    - davidjumani
    - dims
    - rohityadavcloud
    privacy: closed
    previously:
    - cluster-api-cloudstack-admins
  cluster-api-provider-cloudstack-maintainers:
    description: ""
    members:
    - davidjumani
    - dims
    - jweite-amazon
    - maxdrib
    - rohityadavcloud
    privacy: closed
    previously:
    - cluster-api-cloudstack-maintainers
  cluster-api-provider-digitalocean-admins:
    description: Admin access to the cluster-api-provider-digitalocean repo
    members:
    - cpanato
    - luxas
    - roberthbailey
    - timoreimann
    - timothysc
    privacy: closed
  cluster-api-provider-digitalocean-maintainers:
    description: Write access to the cluster-api-provider-digitalocean repo
    members:
    - cpanato
    - MorrisLaw
    - prksu
    - timoreimann
    - timothysc
    privacy: closed
  cluster-api-provider-gcp-admins:
    description: admin access to cluster-api-provider-gcp
    members:
    - cpanato
    - dims
    - richardcase
    privacy: closed
  cluster-api-provider-gcp-maintainers:
    description: write access to cluster-api-provider-gcp-maintainers
    members:
    - cpanato
    - dims
    - richardcase
    privacy: closed
  cluster-api-provider-kubemark-admins:
    description: admin access to cluster-api-provider-kubemark
    members:
    - benmoss
    - elmiko
    - justinsb
    - neolit123
    - timothysc
    - vincepri
    privacy: closed
  cluster-api-provider-kubemark-maintainers:
    description: write access to cluster-api-provider-kubemark
    members:
    - benmoss
    - elmiko
    privacy: closed
  cluster-api-provider-kubevirt-admins:
    description: admin access to cluster-api-provider-kubevirt
    members:
    - agradouski
    - cchengleo
    - davidvossel
    - justinsb
    - neolit123
    - timothysc
    - vincepri
    privacy: closed
  cluster-api-provider-kubevirt-maintainers:
    description: write access to cluster-api-provider-kubevirt
    members:
    - agradouski
    - cchengleo
    - davidvossel
    privacy: closed
  cluster-api-provider-nested-admins:
    description: admin access to cluster-api-provider-nested
    members:
    - christopherhein
    - fabriziopandini
    - Fei-Guo
    - justinsb
    - neolit123
    - timothysc
    - vincepri
    privacy: closed
  cluster-api-provider-nested-maintainers:
    description: write access to cluster-api-provider-nested
    members:
    - christopherhein
    - Fei-Guo
    - resouer
    - zhuangqh
    privacy: closed
  cluster-api-provider-openstack-admins:
    description: admin access to cluster-api-provider-openstack
    members:
    - jichenjc
    - lentzi90
    - mdbooth
    - seanschneeweiss
    - tobiasgiese
    privacy: closed
  cluster-api-provider-openstack-maintainers:
    description: write access to cluster-api-provider-openstack
    members:
    - hidekazuna
    - jichenjc
    - mdbooth
    - seanschneeweiss
    - tobiasgiese
    privacy: closed
  cluster-api-provider-packet-admins:
    description: Admin access to cluster-api-provider-packet repo
    members:
    - cprivitere
    - deitch
    - detiber
    - displague
    privacy: closed
  cluster-api-provider-packet-maintainers:
    description: Write access to the cluster-api-provider-packet repo
    members:
    - cprivitere
    - deitch
    - detiber
    - displague
    privacy: closed
  cluster-api-provider-vsphere-admins:
    description: Admin access to the cluster-api-provider-vsphere repo
    members:
    - akutz
    - frapposelli
    - srm09
    - yastij
    privacy: closed
  cluster-api-provider-vsphere-maintainers:
    description: Write access to the cluster-api-provider-vsphere repo
    members:
    - akutz
    - figo
    - frapposelli
    - randomvariable
    - sidharthsurana
    - srm09
    - vincepri
    - yastij
    privacy: closed
  cluster-api-release-team:
    description: Release team of Cluster API
    members:
    - aniruddha2000
    - CecileRobertMichon
    - chiukapoor
    - chrischdi
    - furkatgofurov7
    - g-gaston
    - hackeramitkumar
    - joekr
    - johannesfrey
    - killianmuldoon
    - nawazkh
    - Prajyot-Parab
    - sbueringer
    - tobiasgiese
    privacy: closed
  etcdadm-admins:
    description: Admin access to the etcdadm repo
    members:
    - dlipovetsky
    - justinsb
    privacy: closed
  etcdadm-maintainers:
    description: Write access to the etcdadm repo
    members:
    - dlipovetsky
    - justinsb
    privacy: closed
  image-builder-admins:
    description: admin access to image-builder
    members:
    - jsturtevant
    - kkeshavamurthy
    - mboersma
    privacy: closed
  image-builder-maintainers:
    description: write access to image-builder
    members:
    - jsturtevant
    - kkeshavamurthy
    - mboersma
    privacy: closed
  kubespray-admins:
    description: Admin access to the kubespray repo
    members:
    - ant31
    - chadswen
    - floryut
    - mattymo
    privacy: closed
  kubespray-maintainers:
    description: Write access to the kubespray repo
    members:
    - ant31
    - chadswen
    - cristicalin
    - floryut
    - mattymo
    - miouge1
    - oomichi
    - yankay
    privacy: closed
  logical-cluster-admins:
    description: Admin access to the logical-cluster repo
    members:
    - fabriziopandini
    - vincepri
    privacy: closed
  logical-cluster-maintainers:
    description: Write access to the logical-cluster repo
    members:
    - fabriziopandini
    - vincepri
    privacy: closed
  minikube-gui-admins:
    description: Admin access to the minikube-gui repo
    members:
    - medyagh
    - spowelljr
    privacy: closed
  minikube-gui-maintainers:
    description: Write access to the minikube-gui repo
    members:
    - medyagh
    - spowelljr
    privacy: closed
