teams:
  k8s.io-admins:
    description: Admin access to kubernetes/k8s.io
    members:
    - ameukam
    - dims
    - k8s-infra-ci-robot
    - spiffxp
    - thockin
    privacy: closed
    repos:
      k8s.io: admin
  sig-k8s-infra:
    description: sig-k8s-infra members
    maintainers:
    - cblecker
    - idvoretskyi
    - nikhita
    members:
    - ameukam
    - BenTheElder
    - BobyMCbobs
    - chewong
    - claudiubelu
    - cpanato
    - dims
    - hh
    - ixdy
    - justinsb
    - listx
    - munnerz
    - puerco
    - Riaankl
    - rikatz
    - spiffxp
    - stp-ip
    - thockin
    privacy: closed
    teams:
      sig-k8s-infra-leads:
        description: sig-k8s-infra chairs and technical leads
        members:
        - ameukam
        - dims
        - spiffxp
        - thockin
        privacy: closed
      k8s-infra-aws-admins:
        description: granted access to the k8s-infra AWS account
        maintainers:
        - idvoretskyi
        members:
        - justinsb
        - thockin
        privacy: closed
      k8s-infra-gcp-auditors:
        description: granted read-only access to the k8s-infra GCP org (excluding secrets)
        maintainers:
        - cblecker
        - idvoretskyi
        members:
        - BobyMCbobs
        - hh
        - justinsb
        - puerco
        - Riaankl
        - spiffxp
        - thockin
        privacy: closed
      k8s-infra-gcp-org-admins:
        description: granted owner access to the k8s-infra GCP org
        members:
        - ameukam
        - dims
        - spiffxp
        - thockin
        privacy: closed
      k8s-infra-group-admins:
        description: granted run access to kubernetes.io groups reconciler
        maintainers:
        - cblecker
        members:
        - dims
        - spiffxp
        - thockin
        privacy: closed
      registry.k8s.io-admins:
        description: Admin access to kubernetes/registry.k8s.io
        members:
        - ameukam
        - bentheelder
        - dims
        - spiffxp
        - thockin
        privacy: closed
      registry.k8s.io-maintainers:
        description: Write access to kubernetes/registry.k8s.io
        members:
        - ameukam
        - bentheelder
        - dims
        - spiffxp
        - thockin
        privacy: closed
