teams:
  sig-cloud-provider:
    description: Parent Team for SIG Cloud Provider
    members:
    - andrewsykim
    - calebamiles
    - cheftako
    - hogepodge
    - jhorwit2
    - justaugustus
    - mcrute
    - nckturner
    - yastij
    privacy: closed
    teams:
      cloud-provider-sample-admins:
        description: ""
        members:
        - andrewsykim
        - cheftako
        - mcrute
        privacy: closed
        repos:
          cloud-provider-sample: admin
      cloud-provider-sample-maintainers:
        description: ""
        members:
        - andrewsykim
        - cheftako
        - mcrute
        privacy: closed
        repos:
          cloud-provider-sample: write
      sig-cloud-provider-alibaba-admins:
        description: ""
        members:
        - aoxn
        - cheyang
        - gujingit
        privacy: closed
        repos:
          cloud-provider-alibaba-cloud: admin
      sig-cloud-provider-aws-admins:
        description: "Admin access to k8s.io/cloud-provider-aws"
        members:
        - andrewsykim
        - dims
        - justinsb
        - nckturner
        privacy: closed
        repos:
          cloud-provider-aws: admin
      sig-cloud-provider-aws-maintainers:
        description: "Write access to k8s.io/cloud-provider-aws"
        members:
        - andrewsykim
        - cartermckinnon
        - justinsb
        - nckturner
        - olemarkus
        privacy: closed
        repos:
          cloud-provider-aws: write
      sig-cloud-provider-api-reviews:
        description: ""
        members:
        - andrewsykim
        - hogepodge
        privacy: closed
      sig-cloud-provider-bugs:
        description: ""
        members:
        - andrewsykim
        - hogepodge
        privacy: closed
      sig-cloud-provider-feature-requests:
        description: ""
        members:
        - andrewsykim
        - hogepodge
        privacy: closed
      sig-cloud-provider-misc:
        description: ""
        members:
        - andrewsykim
        - hogepodge
        privacy: closed
      sig-cloud-provider-pr-reviews:
        description: ""
        members:
        - andrewsykim
        - hogepodge
        - nckturner
        privacy: closed
      sig-cloud-provider-proposals:
        description: ""
        members:
        - andrewsykim
        - hogepodge
        privacy: closed
      sig-cloud-provider-test-failures:
        description: ""
        members:
        - andrewsykim
        - hogepodge
        privacy: closed
  sig-cloud-provider-admins:
    description: ""
    members:
    - andrewsykim
    privacy: closed
    repos:
      cloud-provider: admin
      cloud-provider-alibaba-cloud: admin
  sig-cloud-provider-leads:
    description: ""
    members:
    - andrewsykim
    - cheftako
    - nckturner
    privacy: closed
